:: Install embedding2 and pos2 for all languages in the Universal POS Tables
polyglot download embedding2.ar pos2.ar &:: Arabic
polyglot download embedding2.bg pos2.bg &:: Bulgarian
polyglot download embedding2.bn pos2.bn &:: Bengali
polyglot download embedding2.ca pos2.ca &:: Catalan
polyglot download embedding2.cs pos2.cs &:: Czech
polyglot download embedding2.da pos2.da &:: Danish
polyglot download embedding2.de pos2.de &:: German
polyglot download embedding2.el pos2.el &:: Greek
polyglot download embedding2.en pos2.en &:: English
polyglot download embedding2.es pos2.es &:: Spanish
polyglot download embedding2.et pos2.et &:: Estonian
polyglot download embedding2.eu pos2.eu &:: Basque
polyglot download embedding2.fa pos2.fa &:: Persian
polyglot download embedding2.fi pos2.fi &:: Finnish
polyglot download embedding2.grc pos2.grc &:: Ancient Greek
polyglot download embedding2.he pos2.he &:: Hebrew
polyglot download embedding2.hi pos2.hi &:: Hindi
polyglot download embedding2.hr pos2.hr &:: Croatian
polyglot download embedding2.hu pos2.hu &:: Hungarian
polyglot download embedding2.it pos2.it &:: Italian
polyglot download embedding2.ja pos2.ja &:: Japanese
polyglot download embedding2.la pos2.la &:: Latin
polyglot download embedding2.mt pos2.mt &:: Maltese
polyglot download embedding2.nl pos2.nl &:: Dutch
polyglot download embedding2.pl pos2.pl &:: Polish
polyglot download embedding2.pt pos2.pt &:: Portuguese
polyglot download embedding2.ro pos2.ro &:: Romanian
polyglot download embedding2.ru pos2.ru &:: Russian
polyglot download embedding2.sk pos2.sk &:: Slovak
polyglot download embedding2.sl pos2.sl &:: Slovenian
polyglot download embedding2.sv pos2.sv &:: Swedish
polyglot download embedding2.ta pos2.ta &:: Tamil
polyglot download embedding2.te pos2.te &:: Tegulu
polyglot download embedding2.tr pos2.tr &:: Turkish
polyglot download embedding2.zh pos2.zh &:: Chinese